---
title: "Task: Create a new Quarto website project"
format: 
  html:
    page-layout: full
---

\

## Instructions

-   RStudio - New Project - New Directory - Quarto Website

-   Click on Render to have a look at the template.

::: {style="max-width:608px"}
::: {style="position:relative;padding-bottom:66.118421052632%"}
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&amp;playerId=kaltura_player&amp;entry_id=1_rpoljyji&amp;flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&amp;wid=1_es0y8p03" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="RStudio: Create new Quarto website project" style="position:absolute;top:0;left:0;width:100%;height:100%">

</iframe>
:::
:::

## Troubleshooting

-   Error: "C:/Program is not recognised as an internal or external command, operable program or batch file."
    -   Make sure project name and parent folders have no spaces in them (only an issue on some Windows computers).
-   "Quarto Website" is not listed as an option.
    -   Make sure your RStudio is version 2022.07.01 or greater.
