---
title: "Task: Add R code to your website"
format: 
  html:
    page-layout: full
---

## Instructions

-   Insert a code chunk.
    -   Use the green **+C** button or `Ctrl+Alt+I`/`Cmd+Opt+I`.
-   Add in R code, for example:

```{r}
#| eval: false
library(tidyverse)
library(palmerpenguins)

penguins %>% 
  ggplot(aes(species, flipper_length_mm, fill = sex, size = body_mass_g)) +
  geom_jitter(shape = 21, colour = "grey", alpha = 0.8) +
  scale_fill_viridis_d() +
  theme_bw()
```

-   Hide the R code and its warnings.
    -   Search online for 'quarto output options' to copy the relevant YAML options.

    -   Displaying code is referred to as 'echo'.

::: {style="max-width:608px"}
::: {style="position:relative;padding-bottom:66.118421052632%"}
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/2010292/sp/201029200/embedIframeJs/uiconf_id/32599141/partner_id/2010292?iframeembed=true&amp;playerId=kaltura_player&amp;entry_id=1_agn58jyw&amp;flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&amp;wid=1_wl3zmwum" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="R code and chunk options in Quarto" style="position:absolute;top:0;left:0;width:100%;height:100%">

</iframe>
:::
:::
